### ISSUE TITLE
a prior distribution which has two parameter

### ISSUE THREAD

**Issue by Zhou-haiyang** [pymc-devs/resources#101]
I have a function ：Y = beta_1+beta_2 * X
and I want to construct a prior beta = (beta_1 , beta_2) iid Normal (mu, covariance matrix）
how to deal with this problem
[https://www.sciencedirect.com/science/article/pii/S0142112320300426](url)
https://doi.org/10.1016/j.ijfatigue.2020.105511

**Comment by AlexAndorra** [comment]
Hi,
Thanks for your question. As this is more a modeling one than an issue with the code in this repo, can you please post it to [our Discourse](https://discourse.pymc.io/)?
Thanks and have a nice day 🖖
