### ISSUE TITLE
resources/Rethinking_2/Chp_05.ipynb

### ISSUE THREAD

**Issue by yongduek** [pymc-devs/resources#102]
1. 5.13 (In [23])
  - the observation variable is 'Marriage_std', so its name should have been 'Marriage_std' instead of 'divorce_std'.
  - below is the code 5.13.
```
with pm.Model() as m_5_4:
    a = pm.Normal("a", 0, 0.2)
    bAM = pm.Normal("bAM", 0, 0.5)
    sigma = pm.Exponential("sigma", 1)

    mu = pm.Deterministic("mu", a + bAM * data["MedianAgeMarriage_std"])

    marriage_std = pm.Normal(
        "divorce_std", mu=mu, sigma=sigma, observed=data["Marriage_std"].values
    )
    prior_samples = pm.sample_prior_predictive()
    m_5_4_trace = pm.sample()
```

2. 5.15 (In [25])
  - this cell is about posterior predictive check for the observation variable 'divorce_rate_std' whose model number is `m_5_3` (as indicated `m5.3` in the book)
  - so, 5_4 in the whole cell should be replaced by 5_3
  - and 'divorce_std' must be replaced by 'divorce_rate_std' as defined in model `m_5_3`
  - below is 5.15
```
# We can skip most of the code with the posterior predictive plot functionality in pymc3
with m_5_4:
    m_5_4_ppc = pm.sample_posterior_predictive(
        m_5_4_trace, var_names=["mu", "divorce_std"], samples=1000
    )

mu_mean = m_5_4_ppc["mu"].mean(axis=0)
mu_hpd = az.hpd(m_5_4_ppc["mu"], credible_interval=0.89)

D_sim = m_5_4_ppc["divorce_std"].mean(axis=0)
D_PI = az.hpd(m_5_4_ppc["divorce_std"], credible_interval=0.89)
```

Hope I am making a correct suggestion.

Many thanks for sharing the wonderful pymc3 codes for the book

**Comment by AlexAndorra** [comment]
Thanks for reporting this @yongduek ! Do you feel like doing a PR to fix it?
