### ISSUE TITLE
Add black formatter to .pre-commit.config

### ISSUE THREAD

**Issue by MarcoGorelli** [pymc-devs/resources#125]
xref this comment https://github.com/pymc-devs/resources/pull/118#issuecomment-726018519

If you're not running pre-commit checks during CI (there's still lots of notebooks that need updating), then even just putting the desired checks in `.pre-commit-config.yaml` might be a good idea so that for any new notebooks which are added, contributors can simply run
```
pre-commit run --files  <notebooks>
```
without having anything other than pre-commit

----

I can take this on later this week if you like

**Comment by AlexAndorra** [comment]
Hey @MarcoGorelli !
I'm a bit confused: wasn't this setup already done with PR #123 ? I was under the impression that with this PR merged, checks against isort/black/pyugrade would be run by `pre-commit-ci`?
And in case of failures, contributors would indeed just have to run `pre-commit run --files  <notebooks>` locally (at least until we allow `pre-commit-ci` to do the changes itself). Am I mistaken?

**Comment by MarcoGorelli** [comment]
#123 just added 'isort' and 'pyupgrade' still need to do 'black' so this is just here as a reminder

**Comment by AlexAndorra** [comment]
Ah ok, thanks for the clarification 👌

**Comment by MarcoGorelli** [comment]
closing this is already mostly there (and it's arguably not too important to have strict checks in the `resources` repo :smile: )
