### ISSUE TITLE
Solved Exercises for Chapters 3-

### ISSUE THREAD

**Issue by rroberts76** [pymc-devs/resources#133]
Are there solved problems for end of chapter exercises for Chapters 3-9?

**Comment by AlexAndorra** [comment]
Hi @rroberts76 ! Yes, @AidanMar [is working on this](https://github.com/pymc-devs/resources/pull/119) 🎉 
If you want you can jump in and help him for further chapters, starting from chapter 10?

**Comment by rroberts76** [comment]
Would be happy to help to the best of my ability.  I am quite a novice, so
caveat emptor.
