### ISSUE TITLE
Adding 'Doing Bayesian Data Analysis'?

### ISSUE THREAD

**Issue by rosgori** [pymc-devs/resources#14]
Are you guys planning to add a new resource to this page? The book I have in mind is 'Doing Bayesian Data Analysis' from John K. Kruschke. There are at least two repositories in [github.com](github.com) where you can find `pymc3` as a replacement for `Stan`:

- https://github.com/aloctavodia/Doing_bayesian_data_analysis
- https://github.com/JWarmenhoven/DBDA-python

**Comment by junpenglao** [comment]
That's a great idea, cc @aloctavodia @jwarmenhoven.

**Comment by JWarmenhoven** [comment]
What will be the benefit of migrating these repositories? They are referenced in the PyMC3 documentation. http://docs.pymc.io/#learn-bayesian-statistics-with-a-book-together-with-pymc3

**Comment by aloctavodia** [comment]
My port of the first edition is outdated, if we are going to move it here we should updated. Maybe we should focus all efforts on @JWarmenhoven port of the second edition. 

When I suggested moving statistical rethinking code under pymcdevs I was thinking about long term maintenance and also I did not like to have a repository under my number with several other contributors, putting inside and organization sounds like a better choice.

**Comment by twiecki** [comment]
@aloctavodia In that case you should probably add a link to @JWarmenhoven's version.

**Comment by aloctavodia** [comment]
@twiecki good idea! Done it. I also just realize that I did a code update six month ago, not that bad! Will check if another one is necessary.

**Comment by aloctavodia** [comment]
@rosgori Are you still interesting in adding this book? If not I think we can just close this issue.

**Comment by rosgori** [comment]
You can close this issue.
