### ISSUE TITLE
Creating Environment Conda

### ISSUE THREAD

**Issue by MbMeric** [pymc-devs/resources#153]
Hello. i'm stuck at very beginning.
When I want to set up an environment from the environment.yml file, I get the following error.
`conda env create -f environment.yml` 
after that command prompt will return like this:
```
Pip subprocess error:
  Running command git clone -q git://github.com/arviz-devs/arviz.git 'C:\Users\burak\AppData\Local\Temp\pip-req-build-_xjzvgoz'
  Running command git clone -q git://github.com/pymc-devs/pymc3.git 'C:\Users\burak\AppData\Local\Temp\pip-req-build-ijw6axac'
  WARNING: Did not find branch or tag 'master', assuming revision or ref.
  Running command git checkout -q master
  error: pathspec 'master' did not match any file(s) known to git
WARNING: Discarding git+git://github.com/pymc-devs/pymc3.git@master. Command errored out with exit status 1: git checkout -q master Check the logs for full command output.
ERROR: Command errored out with exit status 1: git checkout -q master Check the logs for full command output.

failed

CondaEnvException: Pip failed
```

i suspect the git version and install it but nothing changed.
Any idea ?

**Comment by MarcoGorelli** [comment]
Hey @MbMeric - this is likely because pymc has switched from `master` to `main`

Do you want to make a pull request to fix this in the environment.yml file?

**Comment by MbMeric** [comment]
I'm just a few days old software student and not very familiar with the terms. If I change pymc@master to pymc@main, which I understand from what you said, it can be fixed.

**Comment by MarcoGorelli** [comment]
That's fine, there's a ton of tutorials on how to do this e.g. https://youtu.be/rgbCcBNZcdQ - feel free to ask for help

**Comment by MbMeric** [comment]
thanks it's fixed . Changing pymc@master to pymc@main worked. thanks for your help and i will learn to make a pull request.
