### ISSUE TITLE
 Resources/Rethinking_2/Chp_04.ipynb - Question

### ISSUE THREAD

**Issue by yiftachn** [pymc-devs/resources#157]
Why are we substracting max(post_prod) in :
post = np.mgrid[150:160:0.05, 7:9:0.05].reshape(2, -1).T

likelihood = [
    sum(stats.norm.logpdf(d2.height, loc=post[:, 0][i], scale=post[:, 1][i]))
    for i in range(len(post))
]

post_prod = (
    likelihood
    + stats.norm.logpdf(post[:, 0], loc=178, scale=20)
    + stats.uniform.logpdf(post[:, 1], loc=0, scale=50)
)
post_prob = np.exp(post_prod - max(post_prod))

**Comment by aloctavodia** [comment]
To avoid overflow, this keeps the exponentiated numbers small, because we only care of the relative values of post_prod subtracting a constant is not a problem
