### ISSUE TITLE
Amazon reviewer had an issue with SR book python code

### ISSUE THREAD

**Issue by dsanalytics** [pymc-devs/resources#18]
One Amazon reviewer had an issue with Statistical Rethinking book python code. I didn't have a chance to confirm this. Here's the review:
https://www.amazon.com/gp/customer-reviews/RFZEN0ZWPL2ZA/ref=cm_cr_getr_d_rvw_ttl?ie=UTF8&ASIN=1482253445

--- Excerpt from it ---

Edit: starting in chapter 6, the Jupiter notebooks use pm.compare to compare models. this doesn't work for me, yet. I followed the instructions for installing the notebooks into a conda environment but there appears to be something wrong. The rest of the python code has run without a glitch.

Edit2: the pm.compare code works if you do the following:
Change :
comp_df = pm.compare(traces=[trace_12_4, trace_12_5],
models=[m_12_4, m_12_5], method='pseudo-BMA')
To:
comp_df = pm.compare({m_12_4: trace_12_4, m_12_5: trace_12_5}, method='pseudo-BMA')
pm.compare expects its first argument to be a dictionary. This fix worked every time I tried it.

--------------------

Thanks

**Comment by junpenglao** [comment]
Ohhhhh right the `pm.compare` API changed - interested to submit a PRs?

**Comment by dsanalytics** [comment]
Just reporting what somebody else found. Thanks in advance for your time.

**Comment by aloctavodia** [comment]
This has been fixed

**Comment by dsanalytics** [comment]
Thanks - appreciated!
