### ISSUE TITLE
12.34 rethinking

### ISSUE THREAD

**Issue by BrianMiner** [pymc-devs/resources#27]
I’m confused why the trace of a_actor is multiplied by a_actor_sims? From the book I was under the impression we were to simply replace trace of a_actor with the sims version and average over it. But then again I’m just learning :) . Can you please give me a hint why the code is as it is here?

**Comment by eigenfoo** [comment]
Hi @BrianMiner! I might misunderstand, but it sounds like you have a question about one of our resources. We'd prefer if you directed those kinds of questions to our [discourse forum](https://discourse.pymc.io/), and reserve the issue tracker for actionable maintenance issues for the developers. Thank you!

Closing this issue now.
