### ISSUE TITLE
Rethinking2: Chapter 4, New B-Splines Section

### ISSUE THREAD

**Issue by kenjioman** [pymc-devs/resources#28]
I am attempting to re-create the figures from Section 4.5.2 on Splines from Richard McElreath's [2nd edition of his book](https://xcelab.net/rm/sr2/) (details of the password found on [the github page](https://github.com/rmcelreath/statrethinking_winter2019) -- sorry, since it's not mine to give away, I only feel comfortable pointing to his repo where he tells you how to access the book).

So far, for what works, I have:
```python
import numpy as np
import pandas as pd
import pymc3 as pm
import patsy

%matplotlib inline
import matplotlib.pyplot as plt

# I downloaded the cherry_blossoms.csv data from the main package website
#### Code Block 4.72 ####
df = pd.read_csv('../Data/cherry_blossoms.csv', sep=';', header=0)
df.describe()
# Note, I am being lazy and not trying to create histograms of each of the columns

#### Code Block 4.73 ####
# First, drop any rows where temp was nan
df2 = df[~df.temp.isna()]
num_knots = 15
knot_list = np.quantile(df2.year, q=np.linspace(0,1, num=num_knots))
knot_list

#### Code Block 4.74 ####
# Construct our B matrix (example from
# https://patsy.readthedocs.io/en/latest/spline-regression.html#general-b-splines)
B = patsy.dmatrix("bs(year, knots=knots, degree=3, include_intercept=True)",
                   data={'year': df2.year.values,
                         'knots': knot_list[1:-1]})
B.shape

#### Code Block 4.75 ####
# Plot each of the lines (note, I am skipping the first "intercept" column, which
# the book also skips -- truthfully, I don't know why he had "bs" include an intercept,
# when he later (code block 4.76) seems to use a model that seems to define its own
# intercept "a" term
plt.figure(figsize=(12,3))
for i in range(1, B.shape[1]):
    plt.plot(df2.year, B[:, i])
plt.plot(knot_list, [1 for x in knot_list], '+')
plt.xlabel('year')
plt.ylabel('basis value')
plt.show()
```

Now, to get to my error/ troubles.  I am trying to re-create Code block 4.76.  Here is what I have:
```python
# Set the seed for reproducibility
np.random.seed(123)
with pm.Model() as m4_7:
    a = pm.Normal('a', 6, 10)
    w = pm.MvNormal('w', mu=np.zeros((1, B.shape[1])), cov=np.eye(B.shape[1]), shape=(1, B.shape[1]))
    #w = pm.MvNormal('w', np.zeros(B.shape[1]), np.eye(B.shape[1]))#, shape=B.shape[1])
    #w = pm.Normal('w', mu=0, sd=1)
    mu = a + pm.math.dot(B, w.T)
    sigma = pm.Exponential(1)
    T = pm.Normal('T', mu, sigma, observed=df2.temp)
    trace = pm.sample(draws=1000, tune=1000, discard_tuned_samples=True)
```

However, when I do that, I get a blank AssertionError:
```python
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-77-9e58e06afc81> in <module>
      6     #w = pm.MvNormal('w', np.zeros(B.shape[1]), np.eye(B.shape[1]))#, shape=B.shape[1])
      7     #w = pm.Normal('w', mu=0, sd=1)
----> 8     mu = a + pm.math.dot(B, w.T)
      9     sigma = pm.Exponential(1)
     10     T = pm.Normal('T', mu, sigma, observed=df2.temp)

~/miniconda3/envs/srt/lib/python3.7/site-packages/theano/tensor/basic.py in dot(a, b)
   6077 
   6078     """
-> 6079     a, b = as_tensor_variable(a), as_tensor_variable(b)
   6080 
   6081     if a.ndim == 0 or b.ndim == 0:

~/miniconda3/envs/srt/lib/python3.7/site-packages/theano/tensor/basic.py in as_tensor_variable(x, name, ndim)
    192 
    193     try:
--> 194         return constant(x, name=name, ndim=ndim)
    195     except TypeError:
    196         try:

~/miniconda3/envs/srt/lib/python3.7/site-packages/theano/tensor/basic.py in constant(x, name, ndim, dtype)
    230 
    231     """
--> 232     x_ = scal.convert(x, dtype=dtype)
    233 
    234     bcastable = [d == 1 for d in x_.shape]

~/miniconda3/envs/srt/lib/python3.7/site-packages/theano/scalar/basic.py in convert(x, dtype)
    282             if x_.size == 0 and not hasattr(x, 'dtype'):
    283                 x_ = np.asarray(x, dtype=config.floatX)
--> 284     assert type(x_) in [np.ndarray, np.memmap]
    285     return x_
    286 

AssertionError: 
```

I've tried a few other ways of encoding pm.MvNormal or the parameter "w", as best as I could figure from the documentation, but I keep getting errors.  So, for my question -- **what can I do to get this working?  Am I missing something, or is trying to do this kind of matrix multiplication not supported?**

Thanks for your help!
PS, my conda environment is [here](https://github.com/kenjioman/StatisticalRethinking/blob/master/environment.yml). Also, if you decide to update the [code block examples for chapter 4](https://github.com/pymc-devs/resources/blob/master/Rethinking/Chp_04.ipynb) here and want to re-use any of my code above, feel free!

**Comment by junpenglao** [comment]
pm.math.dot does not understand data type for `B`, which is a DesignMatrix
Try:
```python
    mu = a + pm.math.dot(np.asarray(B), w.T)
    sigma = pm.Exponential('sd', 1) <- there is a mistake here also
```

**Comment by kenjioman** [comment]
Thank you so much for your quick reply!  I think this will work! (at least, it didn't throw an error message, and it's in the middle of sampling).  Also, I recognize the other error you pointed out -- thanks for bringing it to my attention as well!

**Comment by kenjioman** [comment]
Just to clarify, in the book, the matrix multiplication is simply used as a tool to assign a unique weight to each column of the B matrix, and sum these products together.  Assigning w as a MvNormal, as above, is I think actually the wrong thing to do, as this causes the sampler to create covariance terms (if I understand correctly), but we actually want all off-diagonal terms to be zero (so, the fix above ran, but the estimated time to completion was turning into almost ~10 hours).

From reading more of the PyMC3 documentation, I think this is the right thing to do:
```python
ws = [pm.Normal(f'w{i}', mu=0, sd=1) for i in range(B.shape[1])]
mu = a + pm.math.dot(np.asarray(B), pm.math.stack(ws).T)
```
(at least, this is only taking ~5 mins per chain, and I think this is the desired behavior from the chapter).

**Comment by junpenglao** [comment]
I think you should avoid the for loop:
```python
ws = pm.Normal('w', mu=0, sd=1, shape = (B.shape[1], 1))
mu = a + pm.math.dot(np.asarray(B), ws)
```

**Comment by kenjioman** [comment]
I did not realize the Normal distribution also came with a shape parameter -- thank you for pointing that out!  Yes, I think this is probably the best solution.

PS, for future reference, where can I go to see all the acceptable kwargs for these distributions?  Going to the main https://docs.pymc.io/api/distributions/continuous.html#pymc3.distributions.continuous.Normal page only lists that you can input kwargs, but not what some of them might actually be

**Comment by kenjioman** [comment]
@junpenglao I just tried your fix above and it went back to being very slow (~5 or more seconds per iteration instead of 5-6 iterations per second, which the for loop solution had).  So, for my education:

Why is the for loop solution not good, or what benefits does the non-for loop solution provide?  Thanks again for your help!

**Comment by junpenglao** [comment]
Usually, with a for loop of k steps you generate k theano node, and node building is usually expensive (especially when you have a lot of them).
In your case it is interesting, i dont know exactly why the for-loop is actually faster (in most cases using shape=... is faster). My guess is that it is because all betas are in a very large scale. 
It would be interesting to know that:
- is the speed related to logp evaluation. You can time the two different logp, and/or profile the logp function to see how the graph is compiled differently.

**Comment by kenjioman** [comment]
Sorry, I'm relatively new to pymc3 (and Bayesian modelling as well), so I'm not sure I fully understand your suggestion.  Are you suggesting something like:

```python
%timeit model.logp({ws: 0})
```
for both a model with the for loop, and one with the shape term? (Also, from what I gather, I think I can define a model without the pm.sample line, so it can be defined without it taking forever -- is that correct?)  Or, is there something else specifically that you'd recommend?  Also, in case this is important, `B.shape[1]` = 18 (if I remember correctly -- I'd have to check again tonight, but it's definitely around there (17 or 18)).

**Comment by junpenglao** [comment]
Yes, something like:
```python
pt1 = model_with_forloop.test_point
logp1 = model_with_forloop.logp
%timeit = logp1(pt1)

pt2 = model_without_forloop.test_point
logp2 = model_without_forloop.logp
%timeit = logp2(pt2)
```

**Comment by kenjioman** [comment]
Hi Junpeng!
    I just tried the timings you suggested, and found:

For the model with for loops:
`494 µs ± 190 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)`

And for the model without for loops
`5.28 ms ± 849 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)`

so, it looks like your suspicion was correct about the logp calculations taking longer in the no-for loop model.  Anything else you'd like me to check out?

**Comment by junpenglao** [comment]
Could you share the two model again?
It is a bit surprising - I am wondering what is happening in the graph optimization in the back.

**Comment by kenjioman** [comment]
Sure!  Just so you can replicate it fully, the data used can be found at:
https://github.com/rmcelreath/rethinking/blob/Experimental/data/cherry_blossoms.csv

And the minimum code leading up to it is:
```python
# Necessary imports
import numpy as np
import pandas as pd
import pymc3 as pm
import patsy

# First, import the cherry blossoms data
df = pd.read_csv('cherry_blossoms.csv', sep=';', header=0)
# First, drop any rows where temp was nan
df2 = df[~df.temp.isna()]
# And define the knot positions
num_knots = 15
knot_list = np.quantile(df2.year, q=np.linspace(0,1, num=num_knots))

# Construct our B matrix (example from
# https://patsy.readthedocs.io/en/latest/spline-regression.html#general-b-splines)
B = patsy.dmatrix("bs(year, knots=knots, degree=3, include_intercept=True)",
                   data={'year': df2.year.values,
                         'knots': knot_list[1:-1]})
```

And then, for the two models/ the timings you wanted above:
```python
# Define the two models, so they are both starting fresh.
with pm.Model() as mdl_w_forloop:
    a = pm.Normal('a', 6, 10)
    ws = [pm.Normal(f'w{i}', mu=0, sd=1) for i in range(B.shape[1])]
    mu = pm.Deterministic('mu', a + pm.math.dot(np.asarray(B), pm.math.stack(ws).T))
    sigma = pm.Exponential('sigma', 1)
    T = pm.Normal('T', mu, sigma, observed=df2.temp)
    
with pm.Model() as mdl_no_forloop:
    a = pm.Normal('a', 6, 10)
    ws = pm.Normal('w', mu=0, sd=1, shape=(B.shape[1], 1))
    mu = pm.Deterministic('mu', a + pm.math.dot(np.asarray(B), ws))
    sigma = pm.Exponential('sigma', 1)
    T = pm.Normal('T', mu, sigma, observed=df2.temp)

# And now, for the timings
pt1 = mdl_w_forloop.test_point
logp1 = mdl_w_forloop.logp
%timeit logp1(pt1)
pt2 = mdl_no_forloop.test_point
logp2 = mdl_no_forloop.logp
%timeit logp2(pt2)
```

**Comment by kenjioman** [comment]
PS, I don't know if this is relevant, but I get this warning when I do my imports:
```
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
```

**Comment by junpenglao** [comment]
Oh this is likely related! It seems your theano set up does not take full advantage of faster BLAS libraries.

**Comment by junpenglao** [comment]
Hmmm, something funny is happening in the graph optimization: this is much faster
```python
with pm.Model() as mdl_no_forloop:
    a = pm.Normal('a', 6, 10)
    ws = pm.Normal('w', mu=0, sd=1, shape=B.shape[1])
    mu = pm.Deterministic('mu', a + pm.math.dot(np.asarray(B), ws.T))
    sigma = pm.Exponential('sigma', 1)
    T = pm.Normal('T', mu, sigma, observed=df2.temp)
```
