### ISSUE TITLE
Upgrade to PyMC3 3.6

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/resources#36]
These should all be ported to work with recent pymc3 and arviz.

**Comment by AlexAndorra** [comment]
I can help with that, since I'll also work on porting the exercices and/or homeworks.
From I understood though, there is a 3.7 version coming soon? If so, shouldn't we wait for it?

**Comment by twiecki** [comment]
Yes there is, and there are actually some changes (mainly renaming `varnames` and `vars` to `var_names`). You can for now just use master which will look 99% like 3.7.

**Comment by aloctavodia** [comment]
"Rethinking" has been updated, but BDA3 and BCM are still outdated, right?

**Comment by junpenglao** [comment]
I will do an update on BCM from pymc3 master.

**Comment by AlexAndorra** [comment]
Where are we on this? Can we close? Asking because it looks like most NBs were updated.

**Comment by aloctavodia** [comment]
BCM needs to be updated. I will do it

**Comment by aloctavodia** [comment]
I offered myself to update BCM, but I never find the time, sorry :-( Does anyone else have the time to update it?

**Comment by AlexAndorra** [comment]
Maybe I could do it, but I didn't read that book -- is that a problem? The idea is just to update the syntax to new versions of PyMC and ArviZ?

**Comment by aloctavodia** [comment]
Yes, that's the idea. Thanks for your help
