### ISSUE TITLE
4.61

### ISSUE THREAD

**Issue by bluesky314** [pymc-devs/resources#37]
In 4.61 what does this mean?:

```sample_ppc``` returns values corresponding to the input values (weights in this example). Because the weights are not ordered if we use them with the ```fill_between``` function we will get a mess. For that reason in the following cell we order the weights and the predicted heights

**Comment by aloctavodia** [comment]
The easiest way to understand this is to not order the weights and make a plot. You will see what I mean by "mess" . The reasons this happens is that to plot a line using something like matplotlib you plot a few points and linearly interpolate the values "in the middle". If the pairs [xi, yi] are not ordered (according to the x), then you will not get a straight line.
