### ISSUE TITLE
Statistical Rethinking 2nd Edition

### ISSUE THREAD

**Issue by LarryRiedel** [pymc-devs/resources#40]
The new revision of the book, Statistical Rethinking 2nd Edition, is almost done, and the R code should not be changing much before it is published.  [https://xcelab.net/rm/sr2/](url)

**Comment by canyon289** [comment]
Thanks @LarryRiedel 

Reposting link because the text doesn't match the actual URL
 https://xcelab.net/rm/sr2/

**Comment by aloctavodia** [comment]
@LarryRiedel Thanks for the link and interest. 

The author of Statistical Rethinking, Richard McElreath, have plans to keep working on that draft. He wants to have a more definite version by next September/October. We will start porting the code by that time.

**Comment by AlexAndorra** [comment]
I think we can close this issue, as we're now working on porting the 2nd edition
