### ISSUE TITLE
Chp 11 exercises missing 11H5

### ISSUE THREAD

**Issue by AlexAndorra** [pymc-devs/resources#47]
As discussed in #43 here is a reminder to complete this notebook with answers to 11H5 once the issue with Ordered Logistic is solved. I'll gladly do it
PyMCheers!

**Comment by canyon289** [comment]
I just wanted to stop by and say this your portmanteau made my day. Keep up the good work

**Comment by lucianopaz** [comment]
FYI, @AlexAndorra, I just opened a [PR](https://github.com/pymc-devs/pymc3/pull/3563) that should fix this error

**Comment by AlexAndorra** [comment]
Yeah I just saw that @lucianopaz :tada: Thank you, that's awesome!
When it's merged, I can go on and fulfill my destiny: finish chapter 11 and 12 exercises!

**Comment by aloctavodia** [comment]
Is this still an issue?

**Comment by AlexAndorra** [comment]
The underlying issue is solved on PyMC, but the exercise is still missing from this repo. As this is for the first edition though, I suggest closing and taking care of exercises for the second edition -- of course, if a volunteer wants to finish this, she's welcome but I think it's less of a priority 🙂
