### ISSUE TITLE
WARNING No module named 'mkl'

### ISSUE THREAD

**Issue by lucianopaz** [pymc-devs/resources#5]
I was looking at the notebook for chapter III in the [binder server](https://mybinder.org/v2/gh/pymc-devs/resources/master?filepath=BCM), and when I tried to run the first cell, I got a warning regarding mkl. The full traceback is copied below. Maybe this could lead to numerical discrepancies when running code blocks on binder.

    WARNING (theano.configdefaults): install mkl with `conda install mkl-service`: No module named 'mkl'

    ---------------------------------------------------------------------------
    KeyError                                  Traceback (most recent call last)
    /srv/conda/lib/python3.6/configparser.py in _unify_values(self, section, vars)
       1137         try:
    -> 1138             sectiondict = self._sections[section]
       1139         except KeyError:

    KeyError: 'blas'

    During handling of the above exception, another exception occurred:

    NoSectionError                            Traceback (most recent call last)
    /srv/conda/lib/python3.6/site-packages/theano/configparser.py in fetch_val_for_key(key, delete_key)
        167         try:
    --> 168             return theano_cfg.get(section, option)
        169         except ConfigParser.InterpolationError:

    /srv/conda/lib/python3.6/configparser.py in get(self, section, option, raw, vars, fallback)
        780         try:
    --> 781             d = self._unify_values(section, vars)
        782         except NoSectionError:

    /srv/conda/lib/python3.6/configparser.py in _unify_values(self, section, vars)
       1140             if section != self.default_section:
    -> 1141                 raise NoSectionError(section)
       1142         # Update with the entry specific variables

    NoSectionError: No section: 'blas'

    During handling of the above exception, another exception occurred:

    KeyError                                  Traceback (most recent call last)
    /srv/conda/lib/python3.6/site-packages/theano/configparser.py in __get__(self, cls, type_, delete_key)
        327                 val_str = fetch_val_for_key(self.fullname,
    --> 328                                             delete_key=delete_key)
        329                 self.is_default = False

    /srv/conda/lib/python3.6/site-packages/theano/configparser.py in fetch_val_for_key(key, delete_key)
        171     except (ConfigParser.NoOptionError, ConfigParser.NoSectionError):
    --> 172         raise KeyError(key)
        173 

    KeyError: 'blas.ldflags'

    During handling of the above exception, another exception occurred:

    ModuleNotFoundError                       Traceback (most recent call last)
    /srv/conda/lib/python3.6/site-packages/theano/configdefaults.py in check_mkl_openmp()
       1249     try:
    -> 1250         import mkl
       1251         if '2018' in mkl.get_version_string():

    ModuleNotFoundError: No module named 'mkl'

    During handling of the above exception, another exception occurred:

    RuntimeError                              Traceback (most recent call last)
    <ipython-input-1-2bcb85e206c0> in <module>()
    ----> 1 import pymc3 as pm
          2 import numpy as np
          3 import pandas as pd
          4 import matplotlib.pyplot as plt
          5 import seaborn as sns

    /srv/conda/lib/python3.6/site-packages/pymc3/__init__.py in <module>()
          3 
          4 from .blocking import *
    ----> 5 from .distributions import *
          6 from .external import *
          7 from .glm import *

    /srv/conda/lib/python3.6/site-packages/pymc3/distributions/__init__.py in <module>()
    ----> 1 from . import timeseries
          2 from . import transforms
          3 
          4 from .continuous import Uniform
          5 from .continuous import Flat

    /srv/conda/lib/python3.6/site-packages/pymc3/distributions/timeseries.py in <module>()
    ----> 1 import theano.tensor as tt
          2 from theano import scan
          3 
          4 from pymc3.util import get_variable_name
          5 from .continuous import get_tau_sd, Normal, Flat

    /srv/conda/lib/python3.6/site-packages/theano/__init__.py in <module>()
        122 from theano.printing import pprint, pp
        123 
    --> 124 from theano.scan_module import (scan, map, reduce, foldl, foldr, clone,
        125                                 scan_checkpoints)
        126 

    /srv/conda/lib/python3.6/site-packages/theano/scan_module/__init__.py in <module>()
         39 __contact__ = "Razvan Pascanu <r.pascanu@gmail>"
         40 
    ---> 41 from theano.scan_module import scan_opt
         42 from theano.scan_module.scan import scan
         43 from theano.scan_module.scan_checkpoints import scan_checkpoints

    /srv/conda/lib/python3.6/site-packages/theano/scan_module/scan_opt.py in <module>()
         58 
         59 import theano
    ---> 60 from theano import tensor, scalar
         61 from theano.tensor import opt, get_scalar_constant_value, Alloc, AllocEmpty
         62 from theano import gof

    /srv/conda/lib/python3.6/site-packages/theano/tensor/__init__.py in <module>()
         15 from theano.tensor import opt
         16 from theano.tensor import opt_uncanonicalize
    ---> 17 from theano.tensor import blas
         18 from theano.tensor import blas_scipy
         19 from theano.tensor import blas_c

    /srv/conda/lib/python3.6/site-packages/theano/tensor/blas.py in <module>()
        153 from theano.scalar import bool as bool_t
        154 from theano.tensor import basic as T
    --> 155 from theano.tensor.blas_headers import blas_header_text
        156 from theano.tensor.blas_headers import blas_header_version
        157 from theano.tensor.opt import in2out, local_dimshuffle_lift

    /srv/conda/lib/python3.6/site-packages/theano/tensor/blas_headers.py in <module>()
        985 
        986 
    --> 987 if not config.blas.ldflags:
        988     _logger.warning('Using NumPy C-API based implementation for BLAS functions.')
        989 

    /srv/conda/lib/python3.6/site-packages/theano/configparser.py in __get__(self, cls, type_, delete_key)
        330             except KeyError:
        331                 if callable(self.default):
    --> 332                     val_str = self.default()
        333                 else:
        334                     val_str = self.default

    /srv/conda/lib/python3.6/site-packages/theano/configdefaults.py in default_blas_ldflags()
       1445         if res:
       1446             if 'mkl' in res:
    -> 1447                 check_mkl_openmp()
       1448             return res
       1449 

    /srv/conda/lib/python3.6/site-packages/theano/configdefaults.py in check_mkl_openmp()
       1260 you set this flag and don't set the appropriate environment or make
       1261 sure you have the right version you *will* get wrong results.
    -> 1262 """)
       1263 
       1264 

    RuntimeError: 
    Could not import 'mkl'.  Either install mkl-service with conda or set
    MKL_THREADING_LAYER=GNU in your environment for MKL 2018.

    If you have MKL 2017 install and are not in a conda environment you
    can set the Theano flag blas.check_openmp to False.  Be warned that if
    you set this flag and don't set the appropriate environment or make
    sure you have the right version you *will* get wrong results.

**Comment by twiecki** [comment]
Thanks, we probably need to `conda install mkl`.

**Comment by junpenglao** [comment]
Strangely the `environment.yml` is the same in https://github.com/pymc-devs/resources/blob/master/Rethinking/environment.yml and https://github.com/aloctavodia/Statistical-Rethinking-with-Python-and-PyMC3/blob/master/environment.yml but one is broken but the other is not...

**Comment by ColCarroll** [comment]
I just installed theano on a linux machine, and you actually have to do what the error says: `Either install mkl-service with conda or set MKL_THREADING_LAYER=GNU in your environment for MKL 2018.`
I added `export MKL_THREADING_LAYER=GNU` to the `.bashrc` and it works fine.

**Comment by twiecki** [comment]
better to install mkl, no?

**Comment by ColCarroll** [comment]
Sorry, yes, you need to do both: install mkl *and* set `MKL_THREADING_LAYER=GNU`

**Comment by ColCarroll** [comment]
Oops, just saw this was an issue about the binder server and saw `mkl` wasn't installed there.  You're right, that's the bigger problem.

**Comment by aloctavodia** [comment]
I think this is a general problem with conda, I had the same issue a few weeks ago on a fresh install.

**Comment by hvasbath** [comment]
this cannot be resolved within pymc3, you simply have to define the environment variable as @ColCarroll mentioned above.

**Comment by aloctavodia** [comment]
Is this still a problem?

**Comment by TorokLev** [comment]
I suggest uninstall all mkl related packages by apt or yum on you system and uninstall and install the following packages with 
pip: numpy, scipy, pymc3

It solved my problem
