### ISSUE TITLE
Chp 12 exercises missing last 2 problems

### ISSUE THREAD

**Issue by AlexAndorra** [pymc-devs/resources#50]
As discussed in #43 here is a reminder to complete this notebook with answers to last two problems once the issue with Ordered Logistic is solved. I'll gladly do it
PyMCheers!

**Comment by aloctavodia** [comment]
Is this still an issue?

**Comment by AlexAndorra** [comment]
The underlying issue is solved on PyMC, but the exercises are still missing from this repo. As this is for the first edition though, I suggest closing and taking care of exercises for the second edition -- of course, if a volunteer wants to finish this, she's welcome but I think it's less of a priority 🙂
