### ISSUE TITLE
watermark: extension to easily display versions

### ISSUE THREAD

**Issue by StevenLi-DS** [pymc-devs/resources#57]
There is a jupyter extension to easily display versions:

https://github.com/rasbt/watermark

**Comment by AlexAndorra** [comment]
Just tried it, very useful, thanks Steven!
Depending on what others contributors of this repo think, I can add it to requirements.txt.

As long as we're sharing, I'm using this [jupyter extension to black-format](https://github.com/dnanhkhoa/nb_black) my notebooks - very cool. No need to add to requirements though, as long as we blackify locally.

**Comment by canyon289** [comment]
Hey Steven and Alex,
That extension is great for one off notebooks, I use it myself. In this repo we have the env file though which is pretty sparse but perhaps we need to actually add the versions in.

https://github.com/pymc-devs/resources/blob/master/environment.yml

Do you think that would achieve the same purpose?

**Comment by AlexAndorra** [comment]
Hey Ravin! 
I think this is just to replace the last cell of each notebook (where we explicit the versions used to run the NB). Watermark would provide a quicker, simpler and more robust way to do it. Using it would imply adding it the repo's dependencies though, or else users won't be able to run the NBs. In any case, this is only for informational purposes.

If we want to enforce specific package versions, we can indeed pin them in the yaml file - I'm not sure that's necessary though, as it's not a package. A simple information with watermark seems enough to me.
