### ISSUE TITLE
Chapter 9 book != Chp_09.ipynb

### ISSUE THREAD

**Issue by rybyrnes** [pymc-devs/resources#58]
It looks like `Chapter 10 book == Chp_09.ipynb`, `Chapter 11 book == Chp_10.ipynb` and ...

maybe more are misaligned but I was just looking now for the MCMC stuff from Chapter 9. 

However, `Chapter 9 book != Chp_08.ipynb` code 8.1...looks like then its actually matching the book chapter 8.

**Comment by aloctavodia** [comment]
I do not see this problem. Maybe you are reading from a draft version of the first or second edition?
