### ISSUE TITLE
Ch 3 plots

### ISSUE THREAD

**Issue by dwanneruchi** [pymc-devs/resources#61]
I have been working through Statistical Rethinking & have found your notebooks very helpful! I was able to get some of the intervals of defined boundaries & intervals of defined mass plots built (section 3.2.1 and 3.2.2), specifically figure 3.2. Is this something of interest in a pull request? 

Thanks

**Comment by canyon289** [comment]
Yes it is! Feel free to open one up. Thank you for asking!

**Comment by dwanneruchi** [comment]
Great, PR went through! Today I was able to replicate Fig 3.7 in Python so might try to include that as well in a future PR.
