### ISSUE TITLE
(de)centralize environments

### ISSUE THREAD

**Issue by aloctavodia** [pymc-devs/resources#68]
Currently we have a global environment file. And then some of the books/folders have other environments (BCM, BDA3 and rethinking) but others do not have (BSM, rethinking2).

We should check if the requirements are correct and add [watermark](https://github.com/rasbt/watermark) package.

**Comment by AlexAndorra** [comment]
IMO we should completely decentralize environments: no global file and only local env files, tailored to each book/folder. That way, managing envs will be easier: we'll be able to change Rethinking2 packages without messing up those for BDA3 for instance.
