### ISSUE TITLE
Adding new resources?

### ISSUE THREAD

**Issue by bradleyfay** [pymc-devs/resources#70]
Was wondering if there was any initiative to add resources related this book by Gelman. 

Thanks!

https://www.amazon.com/Analysis-Regression-Multilevel-Hierarchical-Models/dp/052168689X

**Comment by canyon289** [comment]
There is not that I know of! You're welcome to open a PR and start adding
content if you like! Let us know if there's any questions with format of
the repo or contributing guidelines etc. Its a bit more of the unstructured
in this repository versus the official pymc3 one

**Comment by aloctavodia** [comment]
There is an ongoing effort to add [Regression and other stories](https://www.cambridge.org/core/books/regression-and-other-stories/DD20DD6C9057118581076E54E40C372C) here https://github.com/bambinos/Bambi_resources
