### ISSUE TITLE
Trouble installing environment

### ISSUE THREAD

**Issue by adamcc** [pymc-devs/resources#77]
I'm having trouble installing the environment.

> $ conda env create -f environment.yml
> Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies.  Conda may not use the correct pip to install your packages, and they may end up in the wrong place.  Please add an explicit pip dependency.  I'm adding one for you, but still nagging you.

There were some more pip errors, and then when I tried to activate the environment, I got: 

> Could not find conda environment: stat-rethink-pymc3
> You can list all discoverable environments with `conda info --envs`.

Should I try to install PyMC3 in my deafult environment instead?

**Comment by adamcc** [comment]
OK, I think that problem is because the environment name is different from what it says on the homepage.

**Comment by aloctavodia** [comment]
Hi @adamcc sorry about the confusion. I have just created a Pull request to have one environment file per folder/book and remove the central environment (pymc3_resources). This should help people in the future.

Regarding your current problem. You could try with this [environment.yml](https://github.com/pymc-devs/resources/blob/master/Rethinking/environment.yml) file. Or you could run `conda install mkl-service`  to fix the "theano is not compiled" error.

**Comment by adamcc** [comment]
Thanks Ozvaldo, very rapid turnaround! Much appreciated. I can get back to it later this week and update you.

**Comment by adamcc** [comment]
Hi @aloctavodia 
Sorry this took a long time to come back to.

I cloned the full pymcresources repo and tried to create the environment:

`➜  pymc-resources git:(main) cd Rethinking_2
➜  Rethinking_2 git:(main) ls
Chp_02.ipynb            Chp_09.ipynb            Chp_16.ipynb
Chp_03.ipynb            Chp_10.ipynb            Data
Chp_04.ipynb            Chp_11.ipynb            End_of_chapter_problems
Chp_05.ipynb            Chp_12.ipynb            README.md
Chp_06.ipynb            Chp_13.ipynb            environment.yml
Chp_07.ipynb            Chp_14.ipynb            environment_v4.yml
Chp_08.ipynb            Chp_15.ipynb
➜  Rethinking_2 git:(main) conda env create -f environment.yml
Collecting package metadata (repodata.json): done
Solving environment: - - failed

CondaError: KeyboardInterrupt

➜  Rethinking_2 git:(main)`

I ended up interrupting conda as it was `Solving environment` for a very long time.

Do I just need to be more patient, or is something wrong?

**Comment by adamcc** [comment]
Update, I tried the `environment_v4.yml` file instead and it worked!

The `Chp_02.ipynb` notebook works fine, only the warning below.

Thanks for making this collection!

```
/Users/mycomputer/opt/anaconda3/envs/stat-rethink2-pymc_v4/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.3
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
```
