### ISSUE TITLE
WAIC score in chapter 10 in Statistical Rethinking

### ISSUE THREAD

**Issue by rosgori** [pymc-devs/resources#9]
If you read the comments on code [10.24 and 10.29](https://github.com/pymc-devs/resources/blob/master/Rethinking/Chp_10.ipynb), you could think "there is something wrong here, is `pymc3` the origin of this error?" Well, there could be many questions about this, but there are at least two ways to confirm if that WAIC score is right.

The first one is to go to this [page](https://osf.io/cugnr/), download the file `Ch._10_Counting_and_Classification.html` and look for `waic(b10.6, b10.7)`. The result is

```
##                  WAIC     SE
## b10.6         1001.40 331.52
## b10.7         1048.61 328.79
## b10.6 - b10.7  -47.21 166.11
```
I suppose this is good, it's a confirmation of the score given by `pymc3`.

The second way is to use Stan. How? In R, follow this [code](http://discourse.mc-stan.org/t/trying-to-find-waic-for-a-simple-model-from-statistical-rethinking/3991/2). This WAIC score is for `m10.6`

```
            Estimate          SE
elpd_waic   -493.2          163.0
p_waic       110.6          39.9
waic         986.4          326.0
```
You could do the same with `m10.7` or `m10.8` or `m10.9`, if you use the package `rethinking`, those WAIC scores are wrong. The scores given by `pymc3` are correct, so... don't worry.

**Comment by junpenglao** [comment]
Thanks for verifying @rosgori!

**Comment by aloctavodia** [comment]
Should we remove the comments? Or explain our computations are right?

**Comment by rosgori** [comment]
Remove the comments? Maybe. But the reasons for that discrepancy are... well, Richard McElreath explains it better https://discourse.mc-stan.org/t/trying-to-find-waic-for-a-simple-model-from-statistical-rethinking/3991/5
