### ISSUE TITLE
"Doing Bayesian Data Analysis" by Kruschke

### ISSUE THREAD

**Issue by ibobak** [pymc-devs/resources#93]
There is a nice repo for a book of John Kruschke "Doing Bayesian Data Analysis"
https://github.com/aloctavodia/Doing_bayesian_data_analysis

I think it would be good to set at least the link to this resource on the readme page, or to import the code and the notebook to your repo.

**Comment by canyon289** [comment]
Hey!
Pull requests are welcome! Feel free to make one to add this to the README
