### ISSUE TITLE
Rethinking2 - Ch5 - Inconsistant Notebook Outputs

### ISSUE THREAD

**Issue by JeroenSchmidt** [pymc-devs/resources#97]
I'm quite new to pymc3 so apologies if this is a dumb question.

I'm going through the code examples for the Statistical Rethinking 2 book and I noticed that the plots within the repo are not the same as the plots I get when I run the notebook. 

I made sure to install the conda enviroment from the yml within this repo.
```
pymc3                     3.9.2
arviz                     0.9.0
```

**Code 5.3**

**Within the repo**
![image](https://user-images.githubusercontent.com/25979801/87313487-3a8b7780-c522-11ea-9bdc-6a5b5fcc98ef.png)

**What I get**
![image](https://user-images.githubusercontent.com/25979801/87313362-0fa12380-c522-11ea-89b9-47b763236c55.png)

I realized that my notebook was creating 4 chains instead of 2 chains. Now I'm looking into what chains are. I'll close this issue.

**Comment by aloctavodia** [comment]
Chains are different runs of the sampler. The purpose of having more than one chain is diagnostics, either visual (for example you check that KDE/traces looks similar) or numerical like computing r hat.
